### ISSUE TITLE
Spike - Hyrax file versioning does not work in our environments

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1006]
Relates to prior investigation ticket #857. This works in Curate in a local dev environment, but does not work when deployed to our servers (file cannot be found).

Suggest we do a small time boxed investigation of what may be involved to get this working, if we determine we need this functionality.

Basic File Versioning in Nurax:

Edit a Fileset, go to the Versions tab:

![Screen Shot 2020-07-20 at 1.48.49 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/7b688a90-8ad3-48c7-88e2-a6d7dc2f9b5e)

See original file attached to the FileSet
![Screen Shot 2020-07-20 at 1.49.14 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/14758ce8-31f6-486d-a54e-904a57784ad4)

Upload a new file to replace the file in the FileSet
![Screen Shot 2020-07-20 at 1.49.57 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/46cd8a37-33f3-4996-8b9e-5c2ce8065bc8)

Restore a prior version from the history - see the User Activity data show the restoration

![Screen Shot 2020-07-20 at 1.53.04 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/8ce011fb-c65e-4148-be97-3bed3905b016)

**Comment by eporter23** [comment]
@alexBLR I added some screenshots from Nurax-dev that show basic UI functions around versioning a fileset. Here's the sample object: https://nurax-dev.curationexperts.com/concern/file_sets/h415p960b?locale=en

Note that their versioning doesn't seem to update the thumbnail when a new file is uploaded over the old version.

**Comment by eporter23** [comment]
@alexBLR were you going to add some comments or a writeup to this ticket?

**Comment by alexBLR** [comment]
@eporter23 yes. later today

**Comment by alexBLR** [comment]
The current implementation of Curate does not allow us to version files (versioning is turned off) because unlike default hyrax we have multiple files in the fileset.

When we add files to the file set we don't differentiate which file should be version and which is not.

In order to make this implementation work, we need to develop functionality similar to what I did with the preferred file in the file_set.

There are a couple of things we need to decide prior to this implementation.

1) Which files in the file_set we want to be versioned.
2) Whether the functionality should exist when you edit work (update files), edit a specific file in the fileset.
3) The impact of this functionality on our custom design of multiple files in a file_set.

@eporter23
