### ISSUE TITLE
Cannot assign branding images to Collections in Curate - NoMethodError

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1016]
This may be useful for supplying larger size collection thumbnails/display images for the Lux homepage or the View Collection pages in Lux. 

The Hyrax Edit Collection form has a Branding tab which allows adding larger sized banner images for Collection display pages. 

![Screen Shot 2020-02-20 at 10.16.26 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/c25b3b7a-8ec9-4168-bfc8-0dd40438e56d)

When trying to add files this way, we get a` NoMethodError in Hyrax::Dashboard::CollectionsController#update`

![Screen Shot 2020-02-20 at 10.18.33 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/405f17e2-93f5-4553-8424-6770aa53df2a)

**Comment by eporter23** [comment]
@tmiles2 this was Queued but not originally prioritized for this sprint because we received the request to work on this after our sprint had started.

**Comment by eporter23** [comment]
This functionality is working in Nurax stable:

![Screen Shot 2020-03-02 at 11.12.26 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/37ef3451-6f28-4292-b7c8-b7e827945a66)

**Comment by eporter23** [comment]
Updated ticket after discussing with @devanshu-m - we only need the banner image capability to function right now (not the logo option)

**Comment by devanshu-m** [comment]
Notes:

* Enables uploading a banner image for a collection and
saving it. Since we have changed the uploaded_files table provided by
hyrax, we need to add a new column to the table called collection_banner
that will be used to upload a file using carrierwave.
* We are also overwriting the add_new_banner method because we need to
reference collection_banner_url instead of the default provided by
hyrax.

Collection edit:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/097febd5-28fa-40b9-b23a-0a9d6aca1bb6)

Collection show page:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/fc4eba15-5332-4b63-996a-0b96ad8c7a8b)
