### ISSUE TITLE
Deliver constrained size options for low resolution download visibility settings

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1054]
This ticket should follow work done to adjust the Download options presented in the UV - #984.

This is also dependent on the Low Resolution image delivery work in progress from DCE.

For access control scenarios that permit viewing and downloading only a reduced resolution image, we need to constrain the maximum size that can be downloaded, and also remove the additional download size options that display by default.

The low resolution maximum height should be 400 px, and the width should scale according to the original image aspect ratio.

Applicable Curate Visibility values 

Emory Low Download (_emory_low_)

Additional notes:
[Mockup of UV Download menu before and after](https://docs.google.com/document/d/1dwfvqkNMfQIxluWQsttGsJH5zj4cUw1RopWyz6q0VVY/edit#)
[DCE summary of access controls and naming conventions](https://docs.google.com/spreadsheets/d/1JGND3IjTK0kvqkKKX0Wi0dHxtcYRZD1QQM-BqJjfrBg/edit#gid=1226450121)

Desired output:
![Screen Shot 2020-03-16 at 12.08.41 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ace62b99-9ee2-4b4b-bb5e-1eeac4c68c81)

**Comment by alexBLR** [comment]
https://knowledge.exlibrisgroup.com/Rosetta/Knowledge_Articles/Configure_Universal_Viewer_to_download_original_file

**Comment by alexBLR** [comment]
https://gist.github.com/tomcrane/34180dc6c5c1caf7e244ffd12e64c389

**Comment by devanshu-m** [comment]
PR in lux: https://github.com/emory-libraries/dlp-lux/pull/452

**Comment by devanshu-m** [comment]
* Emory Low Download works have a download specification that makes sure the height of the image being downloaded is always restricted to 400px. In this commit, we change the options (text) that show up in the download dialogue so we can see only one option which is whole image limited to 400px.


Before:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/fea4c2ab-109f-47b4-a707-d15bd239cdcf)

After:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/d80f1075-c640-44e1-8c93-0f866ad99b54)


* Download options:
  * currentViewDisabledPercentage is set to 0, because the width and the height of the actual image will always be greater, and this will hide the current view download button (refer: https://github.com/UniversalViewer/universalviewer/blob/2a08b8aa87dce7dd5d4d6c65c63df495bebe9775/src/extensions/uv-seadragon-extension/DownloadDialogue.ts#L383)
  * confinedImageSize is set to a high width because the Whole Image Low Res option will be hidden as long as the width of the actual image is lesser than the confinedImageSize option (refer: https://github.com/UniversalViewer/universalviewer/blob/2a08b8aa87dce7dd5d4d6c65c63df495bebe9775/src/extensions/uv-seadragon-extension/DownloadDialogue.ts#L611)

**Comment by eporter23** [comment]
I tested this in Lux on Emory Low Download objects and it is working as expected.
