### ISSUE TITLE
Curate-test and prod dashboard errors - "translation missing: en.hyrax.dashboard.my.heading.visibility"

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1099]
Curate arch, test and prod are showing errors in the filter by Visibility and Collection drop-downs. We especially need to be able to filter by visibility right now to continue with access control testing.

![Screen Shot 2020-03-20 at 9.26.05 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d7d75576-799f-4648-85c9-f187cb27d861)

**Comment by SolomonHD** [comment]
This is probably related to my rebuilds of curate last night. Where do these settings get saved and how do we move it to the shared drive?

**Comment by SolomonHD** [comment]
This is a more complicated issue than I originally thought. Solution will require a code change on both dlp-curate and cor-cm. 

dlp-curate needs a new config option and environment variable called BRANDING_PATH, this will control where the banners are placed after hyrax imports them. In order for these to persist between builds branding_path needs to point to an EFS mount.

 Also, there needs to be a symblink from the branding_path to the public folder on the rails app itself, if that's not there the banners will not be visible on the site. I added a capistrano task so that this symblink is present when deploying.

**Comment by alexBLR** [comment]
On both curate-test and curate-prod we'll need to run a rake task similar what was mentioned here:

https://github.com/samvera/hyrax/issues/3136

**Comment by eporter23** [comment]
@alexBLR has this been deployed? Do we need to run the rake task? I am still seeing the translation missing message in test and prod.

![Screen Shot 2020-04-09 at 12.24.29 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d8b926d8-a064-4b73-9df8-cf8c2e0e3ede)

![Screen Shot 2020-04-09 at 12.24.36 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/97771e70-f0b3-476d-b07d-233128cccbd8)

**Comment by eporter23** [comment]
I'm still seeing the following in production:

Dashboard > Collections:

![Screen Shot 2020-04-16 at 4.57.44 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/00cf6908-e0a0-44f9-a1be-727dd82bab98)

Dashboard > Works:

![Screen Shot 2020-04-16 at 4.57.51 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/427a9d90-7d29-4a54-9887-2bf18cfac038)

**Comment by bwatson78** [comment]
![Screen Shot 2020-06-19 at 9.46.49 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ffb5a41f-798d-487b-bd59-d3542bfe9f08)

**Comment by bwatson78** [comment]
![Screen Shot 2020-06-19 at 9.44.10 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/7d67d0e6-e827-401c-88ba-8522236e2f32)

PR made: https://github.com/emory-libraries/dlp-curate/pull/1268

**Comment by eporter23** [comment]
Looks good! Ready to go to prod.
