### ISSUE TITLE
Collection banner images lost after deploy/rebuild

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1102]
After the banner image ticket #1016 was deployed I uploaded images for each of the collections in test. The images displayed the day after. As of today 3/20, those images no longer render but the page layout is trying to find them.

![Screen Shot 2020-03-20 at 11.34.30 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/527492ee-f51f-4599-9d8e-b2d7f4910544)

**Comment by SolomonHD** [comment]
This is a more complicated issue than I originally thought. Solution will require a code change on both dlp-curate and cor-cm. 

dlp-curate needs a new config option and environment variable called BRANDING_PATH, this will control where the banners are placed after hyrax imports them. In order for these to persist between builds branding_path needs to point to an EFS mount.

 Also, there needs to be a symlink from the branding_path to the public folder on the rails app itself, if that's not there the banners will not be visible on the site. I added a capistrano task so that this symlink is present when deploying.
