### ISSUE TITLE
Production CSV imports for Langmuir stalling on create filesets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1113]
On 3/26/20 I ran two nearly concurrent imports in -test and -prod (using a different set of 10 works). 

Test finished successfully in 15 minutes. 

In Prod, the import created the metadata for the first work, but stalled out for over an hour at the point of trying to create any filesets.There were no errors in the sidekiq retries.

**Comment by tmiles2** [comment]
3/31/2020: Updates provided by Devanshu in slack: per discussion with Collin and Emily: We discussed two options for the langmuir import issues today, first one was importing works without a collection, this option will not work since the importer requires Emily to specify which collection the works need to belong to. The second option is to import works in a duplicate langmuir (empty) collection and see the pace for the import. We can then copy those works in the original langmuir collection. This can happen after the reindex completes on prod. In the meanwhile, I will look into other potential options around the member_of_collections method in Hyrax.

4/1/2020: Updates provided by Devanshu in slack:  the second option here might also not work for us. I tried adding a work to the langmuir collection through the console yesterday and that took more than an hour before my VPN got disconnected and the pipe broke. In that one hour, I think all that took place was gathering of descendants. I have asked for help in the samvera dev channel.

**Comment by devanshu-m** [comment]
Update:

Even with limited indexing, the call to `member_of_collections` takes a long time to process. At this point, we might want to look at the connection between the application and fedora, or the fedora container, or consider looking at other solutions around the collection size of langmuir. As a test, we are going to try a test load of around 10 works in a brand new collection. This is to test if there is stalling when creating a work and trying to add it to the collection. This test will happen after the ResolrizeJob finishes on prod.

**Comment by eporter23** [comment]
4/7/20 updates: we stopped the production reindex and our next steps will be to looking at 

- disabling SOLRSuggest
- load a batch of 10 Langmuir works into a new collection
- load a batch of 10 Langmuir works into Langmuir

**Comment by eporter23** [comment]
As next steps we will try

- [ ]  restart SOLR in production
- [ ]  importing Langmuir objects in a brand new collection
- [ ]  investigate Fedora specifically while running an import

**Comment by eporter23** [comment]
Closing this because investigation of performance for large collection ingests is ongoing and reflected in additional tickets.
