### ISSUE TITLE
Investigate how to create parent works with no filesets

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#1169]
Primary use case: parent works (e.g. books or serials with multiple volumes or copies) cannot be created using the CSV import process because parent works do not have any direct filesets, and the import won't run if a fileset row is not present for a work. We have been creating those objects manually using the form. Later, if the metadata needs to be updated, we cannot use the CSV bulk update process because there is no deduplication key assigned.

Ideas:

- [ ] Extend the bulk importer so that it will allow creation of works without the presence of fileset rows
- [x] Create a parent work via CSV importer by copying a child volume's work and PDF fileset rows, and assigning a new deduplication key
- [x] Run metadata-only refreshes on parent works via CSV (omitting fileset rows) to confirm if fileset rows are required

**Comment by eporter23** [comment]
We tested the second idea noted above (creating a parent work via CSV import by copying a child volume's info). This worked fine. Since we will delete the starter fileset after it's created, we will need to consider what happens if we run certain types of updates on the works over time (so as not to recreate those unneeded filesets).
