### ISSUE TITLE
User Activity data on FileSets missing after backup and restoration

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1223]
While testing work to redesign the View FileSet page and from reviewing random FileSets in arch and test after backup and restoration, it appears that the user activity data has not migrated along with other data. In reviewing these FileSets in Fedora, they do retain their original creation date and preservation events.

**Goal for this ticket: what is the source data for the table, and how can we backup and restore it in the future?** 

For FileSets created after the restoration in those environments, that table is populated with data showing the depositor and the date the file was attached.

To replicate:

1. View a work in -test that was created before the restoration date
2. View a fileset in the work
3. Look at the User Activity table on the View Fileset page
4. For restored data, the table is blank
5. Look at the equivalent fileset in production
6. For the production data, the table is populated 
7. View a work in -test that was created natively in -test after the restoration date
8. View a fileset in the work
9. Look at the User Activity table on the View Fileset page
10. The data is populated

**Screenshots:**

[FileSet in prod](https://curate.library.emory.edu/concern/parent/2150gb5msd-cor/file_sets/24298sf7sp-cor)
![Screen Shot 2020-06-04 at 2.10.21 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/6b6b7498-bd93-4c96-87b3-720115b3725b)

[Same FileSet in test - restored](https://curate-test.library.emory.edu/concern/parent/2150gb5msd-cor/file_sets/24298sf7sp-cor)
![Screen Shot 2020-06-04 at 2.09.02 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f1e0517b-0286-4892-9db4-0d0cc5181354)

**Comment by eporter23** [comment]
notes from @bwatson78 : The presenter gets events from here: https://www.rubydoc.info/github/samvera/hyrax/Hyrax/WithEvents which pulls the values from RedisEventStore

Is there additional data we need to backup as part of our larger process?

**Comment by alexBLR** [comment]
Main Content Event Job
https://github.com/samvera/hyrax/blob/130c4e600318a9194725b35dd0fd6e19e5108dd9/app/jobs/content_event_job.rb


https://github.com/samvera/hyrax/blob/130c4e600318a9194725b35dd0fd6e19e5108dd9/lib/hyrax/redis_event_store.rb

Based on how the event is getting stored.
1. Creates event, based on object id and the depositor
2. Creates Event ID
3. Stores in Redis


https://github.com/samvera/hyrax/blob/130c4e600318a9194725b35dd0fd6e19e5108dd9/app/models/hyrax/event.rb
Redis integration of the event store


Here are DCE note for for restoration that involved backing up redis. Does middleware backup redis? If not, that should be a part of the strategy
https://curationexperts.github.io/playbook/production/backup_and_restore.html


All content event jobs
https://github.com/samvera/hyrax/blob/master/app/jobs/content_delete_event_job.rb
https://github.com/samvera/hyrax/blob/master/app/jobs/content_deposit_event_job.rb
https://github.com/samvera/hyrax/blob/master/app/jobs/content_depositor_change_event_job.rb
https://github.com/samvera/hyrax/blob/master/app/jobs/content_event_job.rb
https://github.com/samvera/hyrax/blob/master/app/jobs/content_new_version_event_job.rb
https://github.com/samvera/hyrax/blob/master/app/jobs/content_restored_version_event_job.rb
https://github.com/samvera/hyrax/blob/master/app/jobs/content_update_event_job.rb


This is where the event is getting pushed to the event store for depositor
https://github.com/samvera/hyrax/blob/f9fdb50df6893f619aabf24c3a47e55068c281ee/app/models/concerns/hyrax/user.rb#L75-L77


Fetching profile events for depositor
https://github.com/samvera/hyrax/blob/f9fdb50df6893f619aabf24c3a47e55068c281ee/app/models/concerns/hyrax/user.rb#L71-L73


Based on the information provided it looks like Redis wasn’t restored because it tries to get information from redis about the specific object and depositor actions and it can’t find related events.
