### ISSUE TITLE
Persistent URL display in digital-test and arch after restoration

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1251]
After our restoration processs, the persistent URL display in digital-test and digital-arch shows the persistent URL with a production URL instead of one pointing to -test or -arch. 

As a first step, to confirm - was this the prior behavior? If so, this is not a bug but will be enhancement to prioritize later.

Lux-test
![Screen Shot 2020-06-10 at 10.46.47 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d4136694-6f09-48a8-aa61-b631056b457f)

Same object in Curate-test
![Screen Shot 2020-06-10 at 10.46.47 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/c7d8e3ca-be2f-40ca-9405-dc4e81e38aba)

**Comment by bwatson78** [comment]
For ticket #540 (and the eventual PR #560), I was advised to code the PURL to point only to the production environment. The reasoning behind it was that, since the test and arch environments were fluid and didn't have an expectation that objects would be sticking around, hardcoding the purl for only the production site would make sense.

**Comment by eporter23** [comment]
Thanks for confirming, @bwatson78. I'll close this and remove the bug label.
