### ISSUE TITLE
Post-ingest preservation events - log as the initiating user, not depositor

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1264]
For manually initiated post-ingest preservation events such as fixity checking an individual fileset in the UI, we should ensure that the event is recorded as having been performed by the actual system user who initiated the action. It currently appears to default to the depositing user.

Tested in Curate-test:

Kathryn performed a fixity check on this fileset, which had no prior fixity check events, and which was part of a work that I deposited:
https://curate-test.library.emory.edu/concern/parent/187pnvx0tt-cor/file_sets/139x0k6dsk-cor

The fixity check preservation events were generated with my name as the user, but I am not the one who executed them.

![Screen Shot 2020-06-18 at 3.29.58 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/8dcfdb73-5c61-4997-938a-7693bf3c5cc0)

**Comment by eporter23** [comment]
TBD: for the fixity check event specifically, do we need to confirm who the user is when we start running the rolling fixity check job?

**Comment by eporter23** [comment]
TBD: is this a Hyrax bug?

**Comment by bwatson78** [comment]
@eporter23 Inherently, the Hyrax-inherited process isn't aware of the initiating user, since it's passed from the controller and then through two more classes without the the current user being passed along to them. This can be fixed by just making the current user an argument that the two classes down the chain can expect and receive. The only problem arises when the Fixity Checks are performed via rake task. How do you want that be addressed?

It is just a string it takes, but I'm wondering how automated versus informative you want the string to be. We could set it to just `software_engineering`, but that could be one of five of us. I could make it so the rake task takes in a string value for an engineer (something like `bwatson`), but if someone other than you or Kathryn is working on the system, they may not be aware of who we, in software engineering, are, which may not help you much. It's your choice.

**Comment by eporter23** [comment]
@bwatson78 for a UI-based fixity check, it should be the user who clicked the button (e.g. _eporter_). For a rake task, let's set the user to _Curate system_ which will be more meaningful for the long haul of preservation audit trails.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1353

**Comment by eporter23** [comment]
Looks good in prod!
