### ISSUE TITLE
Implement alerts for monitoring

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1289]
- [x] Investigate options
- [ ] Implement solution

**Comment by eporter23** [comment]
Discussed in standup on 6/25: create a DLP-ALERTS listserv for any email alerts generated. Subscribe the current Scrum team members.

**Comment by eporter23** [comment]
Documentation discussion: how alerts are setup, where to get to them (AWS > CloudWatch)

**Comment by libdgg** [comment]
Per the decision of the group, I removed everyone from the DLP-ALERTS-L listserv and will decommission that list. Solomon is working with the group on alternative monitoring alert solutions.

**Comment by SolomonHD** [comment]
We were getting a lot of false positives so I've increased the amount of time the check has to fail before an alarm is triggered. It's now 5 minutes at baseline and I've increases the EFS checks to 15 minutes. I may move them down to 5 minutes later.

Also, since moving to 15 for EFS was still triggering alarms, I changes the check itself so the EFS has 180 seconds to respond before being considered stale (up from 3 seconds)

**Comment by SolomonHD** [comment]
I think the alerts are in a good place. The EFS alerts were generating a large amount of false alarms and I've adjusted settings on the check itself for that. Also I've created a slack channel called #dlp-alerts and implemented a lambda function that will convert alarms to the SNS topic DLP-Alerts to the slack channel.

**Comment by SolomonHD** [comment]
Alert write up: https://wiki.service.emory.edu/display/DLPP/CloudWatch+Alarms
