### ISSUE TITLE
Investigate/test Lux UV configuration in Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1290]
As a pre-cursor to implementation (ticket #1088), some investigation may be needed. 

Based on our understanding of how the access control behavior should function:
1. Authorization to see a work occurs through Curate user group permissions
2. The file resolution and download options in the UV are triggered based on the Visibility assigned to a given work
3. The UV configuration and resolution that is shown to users is _always the same_ for a work, regardless of the user level. A user can either see the work (and its UV) or cannot: we do not show different resolution or download options based on a user's credentials. 

In this ticket, we should first research what was implemented for the Lux UV and identify changes to make in Curate.

- [ ] Confirm changes made to UV configuration for Lux (review commits, etc.)
- [ ] Confirm how the dynamic UV configuration switching occurs in Lux and what needs to be added for Curate
- [ ] Test the Lux UV configuration in curate-arch only
- [ ] Identify any gaps or issues that arise before full implementation

**Comment by eporter23** [comment]
@bwatson78 FYI, we wrote up a prequel ticket for #1088 and this documents our discussion in sprint planning on 6/24. This ticket also clarifies expected behavior for how the access controls function.

**Comment by bwatson78** [comment]
@eporter23 I researched the way that Lux UV permissions are coded and have come up with this summary:

The universal viewer has **three configurations**.
- **Standard Config**: Download, Fullscreen, and Share disabled; Paging Toggle Enabled;
- **Liberal Config**: Download, Fullscreen, and Share enabled; Paging Toggle Enabled;
- **Liberal Low Config**: Fullscreen, and Share enabled; Paging Toggle Enabled; Download Dialogue: Current View and Low Res Option Hidden, whole image restricted to 400px;

**Visibility**
- **"open" OR ("authenticated" AND user_signed_in? true)** = Liberal Config
- **"emory_low" AND user_signed_in? true** = Liberal Low Config
- **Anything Else** = Standard Config

**Conclusion**
- All users see the UV and at least Paging Toggle feature
- If the work is marked "open" or "authenticated" with a user signed in, everything is available
- If a user is signed in but the work is marked "emory_low", then all features are available, but the image is restricted to 400px max.

**Rose Room Notes**
- Since all of the works denoted to the Rose Room are only able to be delivered in the said room, the Universal Viewer doesn't have any restrictions directly related to the room.

My analysis on how to proceed is to follow.

**Comment by bwatson78** [comment]
@eporter23 From the Lux side, the user's role has no bearing on whether they can see a work (or the associated UV), and the UV's configuration relies completely on the `visibility_ssi` value. So, for Curate, my question to you is: are the restrictions that block certain users from seeing the **whole** work page already in place? Are they working as expected? 

If they are, then the Lux configuration is easily transferrable. If they're not, let me know. Although I'm guessing, since it's live, that's already in place.

**Comment by eporter23** [comment]
@bwatson78 thanks for the detailed notes, very good info to have documented. To confirm, for Curate, the desired behavior is already in place to enable which users can see which work pages. So yes, hopefully this is just a matter of applying the UV configuration and toggling behavior.

**Comment by bwatson78** [comment]
@eporter23 I'll move forward with the configuration work.
