### ISSUE TITLE
Regression testing (Production environment)

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1325]
Regression testing in prod after upgrading to Hyrax 3 beta3

https://docs.google.com/spreadsheets/d/1McDhU2RtDI6YDAMoaRFJj-bzBDxLcxpFqvQHRn1NIr0/edit#gid=1719657968

**Comment by kmichaelis** [comment]
Issues identified:


1) Preservation events are not showing up on all filesets (I see them on Langmuir and recently uploaded yearbooks, but nothing else)
2) I’m not able to attach files when I create a work through the form (might this be related to the problem we discussed earlier that is keeping the filesets from attaching in the Langmuir import?)
3) I’m having trouble running fixity checks. The first time the fixity check button is clicked, I get an error that says "We're sorry, something went wrong." I have been able to successfully run the check after refreshing the page and/or returning to the fileset page and trying the button again.

Responses from Devanshu:

Point 1 might be a reindexing issue. We might need to reindex prod.
Point 2 has shown up on test before the fix got in.
I am unsure of point 3.


I created a bug ticket for Point 3.

**Comment by eporter23** [comment]
Testing a little further in prod:

1 - is probably due to filesets in prod needing reindex
2 - seems to be resolved as of 7/14; created a [brand new work with two filesets](https://curate.library.emory.edu/concern/curate_generic_works/443nvx0khq-cor?locale=en)
3 - seems to be working again as of 7/14 after testing a random sampling of works in prod
