### ISSUE TITLE
Regenerate IIIF manifests in prod to reflect Rights Status display

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1352]
Following #1191, we will need to regenerate manifests in all environments (especially production) to show the revised rights status formatting in the More Info pane.

**Comment by bwatson78** [comment]
Curate-Test job started: 2020-07-30T23:47:01Z Job id: 0323161c3e755edd5b319dc3
Curate-Arch job started: 2020-07-30T23:51:24Z Job id: cc40a904ed5381ae229d5d1d
Curate job started: 2020-07-30T23:54:39Z Job id: 243a3fe24fa8a4e313caaeb5

**Comment by eporter23** [comment]
@bwatson78 unfortunately, I'm not seeing any changes in the manifests for the rights statement display? Here's one from test:

![Screen Shot 2020-07-31 at 9.13.01 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/185a1bcd-a721-4a8e-8b60-08d4bb6d351a)

**Comment by bwatson78** [comment]
@eporter23 Correct me if I'm wrong, but I think the regeneration of manifests only happens if the date modified value on the object is different from the creation date of the manifest. Is that right? I'll check.

**Comment by bwatson78** [comment]
@eporter23 I can confirm that. Do you know if that work has been modified since the last manifest generation? Should we also consider a change to that Job/Rake task? It seems to be causing some blockades, at least during development.

**Comment by devanshu-m** [comment]
@eporter23 

Curate-test:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/fa4b6283-3838-46c0-975e-12ec886462ac)

Curate-arch:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/fd2e77e6-20fb-43be-8c33-5b75ccaeb9e8)

Curate-prod is extremely slow (could be because of the ongoing jobs):
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/1b4444af-8bcf-4c98-9cdd-56c70450db5d)
