### ISSUE TITLE
Investigate - how to assign/fix edit group permissions after works are deposited

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1505]
**This is a time boxed investigation ticket (see estimate).**

On the Langmuir Deposit - Sept 2020 collection in curate-test, not all the collection groups were assigned in advance. The deposited works are now only accessible to admins because of this.

When looking at the Edit Work> Sharing tab for these works, it is also not possible to manually assign the appropriate groups because the UI does not find them.

![Screen Shot 2020-09-21 at 9.09.41 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/07f24706-08ba-444a-bdca-f246a2404c08)

To investigate:

1. Is there a way to bulk-assign the correct Rose permission groups to these works?
2. Why do our permission groups not show up in the Edit Work > Relationships tab?

The groups to assign are:

- [x] Manager: rose_manager, repository_manager
- [x] Depositor: rose_depositor
- [x] Viewer: rose_viewer

In SOLR, for works correctly deposited into the Langmuir Source Collection, the permissions appear as:

"read_access_group_ssim":["low_res", "rose_viewer"],
 "edit_access_group_ssim":["admin", "repository_manager", "rose_manager"],

Note:
there doesn't seem to be a record of the rose_depositor group in the SOLR index, does this matter, or are the depositor-level permissions managed more at the individual user level only?

**Comment by alexBLR** [comment]
There is a way to assign new permission groups to the collection. Here is how it is done within curate collection importer.
https://github.com/emory-libraries/dlp-curate/blob/0a50515828f401840decbff1977ce074e6e03538/app/importers/curate_collection_importer.rb#L45-L49

This is the main class that assigns permissions. It has find and create method that help us create new permission if the don't exist.
https://github.com/emory-libraries/dlp-curate/blob/0a50515828f401840decbff1977ce074e6e03538/app/importers/collection_permission_ensurer.rb#L25-L32

That being said, we'll need to create a simple rake that runs CollectionPermissionEnsurer on that collection to assign new permission groups to it. This will allow to manually assign the appropriate groups.

Another way of doing is to re-run the importer with all permission groups.

In order to assign permission groups in bulk for work, we'll also need to see if it is only assign in Solr which seems to be the case.

https://github.com/samvera/hyrax/blob/56a2a0727cdf369c80da21bf2cdf0315ad0687f6/app/helpers/hyrax/hyrax_helper_behavior.rb#L18
https://github.com/samvera/hyrax/blob/130c4e600318a9194725b35dd0fd6e19e5108dd9/app/helpers/hyrax/permission_levels_helper.rb
https://github.com/samvera/hyrax/blob/76c95c3a6201a5d1cc87db873558123eb5c6b6d6/app/views/hyrax/base/_form_share.html.erb

Interestingly, there is permission group edit functionality within bulk_edit hyrax feature
https://github.com/samvera/hyrax/blob/5a9d1be16ee1a9150646384471992b03aab527a5/spec/features/batch_edit_spec.rb#L87

**Comment by eporter23** [comment]
Thanks @alexBLR, fyi @bwatson78 just did some work to manually add groups to 14 works that somehow didn't get their Collection assigned from the CSV importer (which meant they had no groups assigned). I also tried the bulk edit from Hyrax but it returns an error, which pretty much has always been the case.
