### ISSUE TITLE
Managed Collections tab returns application error for Manager and Viewer-level group users

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1516]
When logged in as the new user, attempting to view the [Managed Collections tab](https://curate-test.library.emory.edu/dashboard/collections?locale=en) in the dashboard returns a generic application error. Tiffany also experienced this with her Viewer-level account in Curate prod. I have replicated this in arch, test, and prod.

The new Test EZProxy user account in Curate is assigned to the following groups:

rose_viewer
health_sciences_viewer
oxford_viewer

I also added the tezprox user to the rose_manager group through the Roles UI, and the user still can't access the Managed Collections tab.

![Screen Shot 2020-09-28 at 12.43.43 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/884518bb-42c5-4a71-a3be-725e52eaea49)

The error does not occur when opening the [Managed Works](https://curate-test.library.emory.edu/dashboard/works?locale=en) tab.

![Screen Shot 2020-09-28 at 12.45.21 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/5bcdb072-19c9-4ad7-b829-82fcd24ece9a)

**Comment by bwatson78** [comment]
Error: https://app.honeybadger.io/projects/66999/faults/68124506

This error could be happening because the child presenter has a method defined that is being called in the parent presenter. If they're being used in both, it should only be defined in the parent, so I've moved the definition in the following PR:

https://github.com/emory-libraries/dlp-curate/pull/1518

**Comment by eporter23** [comment]
Tested successfully logged in as a Viewer and Manager level user. Thank you!

**Comment by eporter23** [comment]
Tested again in prod logged in as a Viewer and Manager level user.
