### ISSUE TITLE
Add new Curate user

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1603]
Please add user:

swroberts (Spencer Roberts)

to the pitts_manager user group in Curate.

**Comment by devanshu-m** [comment]
In order to add new users to groups do this: https://wiki.emory.edu/display/DLPP/DLP+Middleware+Common+Tasks

However, if you cannot login as deploy user for whatever reason, login as the default `ec2-user` and then change the linux user from within the ec2 server, as follows:
Logged in as `ec2-user`, use this command: `sudo su - deploy`
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/16f1cd23-36ab-4722-b071-a2b6e67b7594)
This will make sure that you are now deploy user. From here, you can edit the user groups and also run db seed.

**Comment by eporter23** [comment]
Looks good in prod @devanshu-m, is it possible to add this user in the test environment too?

**Comment by devanshu-m** [comment]
Yes will do @eporter23

**Comment by eporter23** [comment]
@kmichaelis I confirmed the user is now in the correct group in prod and test.
