### ISSUE TITLE
Investigate data/indexing requirements for full text searching

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1813]
**Updated with final recommendations:** 
To support the indexing required for full-text search, it will be necessary to retain all the txt and OCR xml files we currently ingest, both at the page and the volume level.

**Original ticket details:**

Related user stories:

_As an end-user, I want to expand my keyword search to include results within the full content of the works in the repository, so that my searches are not restricted to metadata only_

_As an end-user, I want to search within the text of a book I'm previewing in the Universal Viewer, so that I can locate information within the resource directly instead of having to download the PDF and then search within it_

_As a Preservation Curator, I want to only ingest the most useful derivatives for book objects, so that we don't add overhead to the repository's operations such as fixity checking_

Digitized book material currently consists of a mix of volume-level as well as page-level files. As part of our ongoing optimization of book ingests, we want to understand which ingested files may be most useful for indexing purposes if we decide to enable full-text searching in the future.

For digitized books material, we always ingest a PDF of the entire volume along with page-level image files (e.g. TIFF). The digitization team has also started producing OCR and TXT outputs for the entire volume, but previously ingested books will not have these files.

For Kirtas-digitized books we also ingest:

- TXT contents for each individual page
- OCR file for entire volume

For LIMB-digitized books:
- TXT contents of each individual page
- ALTO xml (OCR) file for each page

For this ticket, we should identify what is needed indexing-wise for:
- [ ] Full-text search (across the entire repository)
- [ ] Full-text search (within an individual work's IIIF/universal viewer)

Additional references:
The Samvera Newspapers Working Group has some implementations of full-text search:

- Project repo: https://github.com/samvera-labs/newspaper_works/wiki/Features-List#search-features
- demo site: https://newspaperworks.digitalnewspapers.org/catalog?utf8=✓&locale=en&search_field=all_fields&q=search
- Presentation with info about search configurations: https://repo.samvera.org/concern/generic_works/191ff247-81b3-4ca4-8951-a032eb7ca18d?locale=en 
- See also Blacklight IIIF Search gem: https://github.com/boston-library/blacklight_iiif_search

**Comment by abelemlih** [comment]
@eporter23 @rotated8 The following are my findings regarding to implementing full text search across the entire repository, as well as full text search for each individual work within the IIIF/universal viewer UI.

### Search - Entire Repository

This feature will satisfy the following requirement:

> As an end-user, I want to expand my keyword search to include results within the full content of the works in the repository, so that my searches are not restricted to metadata only

To implement this feature, we will need a new Solr field attached to each Work or FileSet that contains the full text of the resource. This field will allow us to include text of all items in the repository when performing a keyword search, and include in the search results works whose text marches best the keywords searched. The following is a screenshot from the Newspaper Works project where this feature was implemented:

![Screen Shot 2022-09-27 at 1.33.35 AM.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/d88311db-16ab-4892-b08a-fbf6825c0ead)

To add a Solr field that contains the text of a Fileset or Work, we will need to add importing text from all Text/OCR files associated with a given Work/Fileset to the indexing process.

### Search - IIIF Viewer

This feature will satisfy the following requirement:

> As an end-user, I want to search within the text of a book I'm previewing in the Universal Viewer, so that I can locate information within the resource directly instead of having to download the PDF and then search within it

To implement this feature, we will make use of the [blacklight_iiif_search](https://github.com/boston-library/blacklight_iiif_search) gem, which enables text search within the IIIF viewer. Please refer to the following [page](https://www.digitalcommonwealth.org/book_viewer/commonwealth:rr174g946) for a demo of how the gem works. The gem has the following prerequisites:

![Screen Shot 2022-09-27 at 2.55.39 AM.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/a5d78c27-faca-4773-a386-69d81024dafd)

In order to implement the gem successfully, we will need to have Solr field that contains the text of each page associated with each work. This will require importing the text from the Text/OCR files associated with each page of each work during the indexing process.

### Questions

- When performing a keyword search, do we need the search results to list each page of each work where there is a keyword match, or just the parent work?
- When the user clicks on a search result, do we redirect them to the first page of a work where there is a keyword march, or open the parent record starting from its first page?

I am planning on meeting with Emily later this week to discuss the questions above, and refine the requirements of the features mentioned above. Let me know if you have any questions!

**Comment by eporter23** [comment]
After talking with @abelemlih we identified a few more questions to consider such as what type of data is needed for a FileSet level SOLR field is it a type of OCR XML such as ALTO, or simply plain text? If OCR XML is required, is there a particular schema that's needed?

**Comment by eporter23** [comment]
We also confirmed that we will most likely need to continue ingesting both volume-level and page-level text and OCR files to support full text searching in the future. The volume-level files would be helpful for supporting keyword searches in Lux against the whole volume, and the page level files will be helpful for searching within IIIF/Universal Viewer.

**Comment by eporter23** [comment]
@abelemlih this may be of interest - looks like the NewspaperWorks gem creates its own derivative files including text and ALTO. https://github.com/samvera-labs/newspaper_works/wiki/Image-Format-and-Derivative-Notes and https://github.com/samvera-labs/newspaper_works/wiki/Article-segmentation-in-METS-ALTO#page-level-alto

**Comment by abelemlih** [comment]
@eporter23 Regarding IIIF search highlighting, please refer to the following:

The `blacklight_iiif_search` requires the following data for highlighting to work properly:
- IIIF canvas URI of each document
- full text of each page of each document, stored in a field on the Solr record
- text coordinates of each page of each document

The `blacklight_iiif_search` has a `iiif_search_annotation_behavior.rb` file that we can override to achieve the following:
- Specify how to extract the IIIF canvas URI for each document
- Extract the coordinates of the search results from the coordinates XML file that we currently have stored for each page of each document.

As for the full text data, we will need to create a new field (`full_text_...`) where we store the full text of each page. Additionally, we will need to store the full text data of each book or volume separately to ensure full text search across the entire repository only returns works, and not individual filesets.

As for how highlighting is rendered, the gem uses the IIIF canvas, as well the the x,y,weight,height coordinates of the search results to highlight each search result in the IIIF viewer. The following is an example, from the Digital Commonwealth [project](https://www.digitalcommonwealth.org/book_viewer/commonwealth:rr174g946) (developed by the Boston Public Library), of the response returned when performing an IIIF search:

```
{
    "@context": [
        "http://iiif.io/api/presentation/2/context.json",
        "http://iiif.io/api/search/1/context.json"
    ],
    "@id": "https://www.digitalcommonwealth.org/search/commonwealth:rr174g946/iiif_search?q=cuba",
    "@type": "sc:AnnotationList",
    "resources": [
        {
            "@id": "https://ark.digitalcommonwealth.org/ark:/50959/rr174g946/annotation/dn400j49w#0",
            "@type": "oa:Annotation",
            "motivation": "sc:painting",
            "resource": {
                "@type": "cnt:ContentAsText",
                "chars": " gotten their eyeon Cuba, which had a population at that time ofabout 700,000, of whom were about 100"
            },
            "on": "https://ark.digitalcommonwealth.org/ark:/50959/rr174g946/canvas/dn400j49w#xywh=3600,1686,100,33"
        },
        {
            "@id": "https://ark.digitalcommonwealth.org/ark:/50959/rr174g946/annotation/dn400j49w#1",
            "@type": "oa:Annotation",
            "motivation": "sc:painting",
            "resource": {
                "@type": "cnt:ContentAsText",
                "chars": ", Mexico and Colombia having abolished Slavery, determined vn carrying the war to Cuba, and enabling her"
            },
            "on": "https://ark.digitalcommonwealth.org/ark:/50959/rr174g946/canvas/dn400j49w#xywh=3867,1935,99,32"
        },
        {
            "@id": "https://ark.digitalcommonwealth.org/ark:/50959/rr174g946/annotation/dn400j49w#2",
            "@type": "oa:Annotation",
            "motivation": "sc:painting",
            "resource": {
                "@type": "cnt:ContentAsText",
                "chars": " the new Republics, and Cuba and Porto Rieu should de- come the object aud iheaive of it, their forfnes"
            },
            "on": "https://ark.digitalcommonwealth.org/ark:/50959/rr174g946/canvas/dn400j49w#xywh=3824,2705,87,27"
        }
    ],
    "hits": [
        {
            "@type": "search:Hit",
            "annotations": [
                "https://ark.digitalcommonwealth.org/ark:/50959/rr174g946/annotation/dn400j49w#0",
                "https://ark.digitalcommonwealth.org/ark:/50959/rr174g946/annotation/dn400j49w#1",
                "https://ark.digitalcommonwealth.org/ark:/50959/rr174g946/annotation/dn400j49w#2"
            ]
        }
    ],
    "within": {
        "@type": "sc:Layer",
        "total": 3
    },
    "startIndex": 0
}
```

Let me know if you have any additional questions!

**Comment by eporter23** [comment]
@abelemlih with your additional research, can you clarify if for the indexing for the new fields we will need the plain text (.txt) files we currently ingest, or can everything be extracted from the OCR (.xml) files that contain both the text content and coordinates?

**Comment by abelemlih** [comment]
@eporter23 The question is here is what is the tradeoff: faster ingest times or reducing storage cost.

In Solr, we will need to store the full text of each document. We can also add a separate field that contains the text coordinates of the text associated with each document. Alternatively, we store a `json` file that contains the text coordinates of each document, and parse that file when performing search highlighting.

To add the full text to the Solr data of each document, extracting the text from a `.txt` file is a lot faster than parsing the `.xml` file for the data. Even for coordinates, parsing a `.json` file that contains all words with their associated coordinates is more efficient than parsing the xml. Therefore, keeping both the `.txt` and `.xml` OCR files is useful, because the XML can serve as the source of truth, and the `txt` file for full text and `json` file for coordinates can serve as useful derivatives for separate use cases.

If the priority is to reduce storage cost, in exchange for much slower ingests for works with a large amount of text, then keeping the OCR file only works. The full text and text coordinates will be extracted from that file during ingest, and no need to store the additional derivatives.

Let me know if you have any other questions!

**Comment by eporter23** [comment]
Thanks @abelemlih, that is helpful! The concern is not about storage cost because there are very small files. We were hoping to reduce the scale of fixity checking since the majority of our files in storage are these page level txt and xml. But we are managing with it so far, so we'll just plan to keep ingesting what we do currently.
