### ISSUE TITLE
Sorting a work's filesets: change will not save

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1938]
While testing Bulkrax imports, I frequently use the File Manager to re-sort the filesets so they display in correct label/title order, because Bulkrax does not attach the filesets in the original CSV row order. 

For the following work, I can re-sort the filesets but the change fails to save.

https://curate-test.library.emory.edu/concern/curate_generic_works/81937pvmqc-cor/file_manager?locale=en

Other works recently created using Bulkrax in arch and test do save their filesets sort order when changed.

**Comment by bwatson78** [comment]
Preliminary Findings: The reordering is failing when attempting to remove FileSets that are no longer listed in ordered_members.

**Comment by bwatson78** [comment]
The cause of this issue is when multiples of one or more FileSet IDs are added into the the work's `#ordered_members`. When the logic finds the difference between the arrays of existing ordered members and the requested ordered members, two arrays that should be exactly the same aren't because of the duplicate(s).

I've found the solution, which is to pull the value of `ordered_member_ids`, remove the duplicates, empty out the value, and put the right array in. Knowing I can do this outside of ingest without hiccups has led me to moving the association of FileSets to Work to the last process in Bulkrax, and it seems to be working without issue.
