### ISSUE TITLE
Bulkrax importers still showing enqueued entries after import completes

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2081]
There have been several Bulkrax importers recently that continue to show entries in the Entries Enqueued column after the importer has completed running (see attached screenshot for examples). In these cases, all expected filesets appear associated with the work but the work requires manual reindexing for the filesets to display properly.

![Capture.JPG](https://images.zenhubusercontent.com/5d924e9841d63100014d5334/4d8f53dc-74e2-4eb7-8ae5-e18d6edca6cd)

**Comment by bwatson78** [comment]
@kmichaelis In this situation please ping me as soon as all jobs for your next import clear the queue. I can do some digging into logs now to see if there are errors I can tie to this, but I'd love to be able to look at the Work in the rails console before reindexing.

**Comment by bwatson78** [comment]
@kmichaelis I have researched this and found that enqueued entries doesn't link directly to the Jobs that perform the import. Instead, the initial importing process determines how many entries it has to make jobs for and assigns that number to a variable called `enqueued_records`. After each record is imported, the Job should send the command to reduce `enqueued_records` by one. 

Since we see remaining `enqueued_records` in larger numbers when the amount of entries is higher, but I can confirm through the command line that all jobs are marked "Complete", I believe we can tie this to the ActiveFedora persistence issue we've been having when we attempt a large importing of objects or when we are attaching a large number of FileSets to a Work. That means that this won't be a reliable indicator of how many actual Jobs are still in queue. Its best use would be to easily identify which imports had ActiveFedora persistence logjams whenever we see a positive number in the column, but the import is marked "Complete".
