### ISSUE TITLE
Problems completing manifest generation

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2154]
Recently I have had trouble generating manifests for some works after they are ingested. Usually this happens in cases where there were a few filesets that didn't attach to the work during the Bulkrax import, so I have attached them manually after ingest. Sometimes they fail with the following error:

ActionView::Template::Error: Couldn't find FileSet without an ID

They have also failed with this error:

ActionView::Template::Error: Failed to open TCP connection to fedora-cor.internal.emory.edu:80 (execution expired)

These failed jobs are still in the Sidekiq dead queue. 

I've identified a handful of works with this problem:

https://curate.library.emory.edu/concern/curate_generic_works/378tb2rd9g-cor/file_manager?locale=en 

https://curate.library.emory.edu/concern/curate_generic_works/1439zw3stf-cor?locale=en 

https://curate.library.emory.edu/concern/curate_generic_works/416c2fr0wt-cor?locale=en 

https://curate.library.emory.edu/concern/curate_generic_works/4579s4mxtw-cor?locale=en 

https://curate.library.emory.edu/concern/curate_generic_works/102c866vsv-cor?locale=en 

https://curate.library.emory.edu/concern/curate_generic_works/747dr7sskr-cor?locale=en&page=27 

https://curate.library.emory.edu/concern/file_sets/3483j9kfx0-cor?locale=en

**Comment by bwatson78** [comment]
Preliminary Findings: It looks like this issue is being caused by nil values being saved into the Work's `ordered_members`. This is because of the false completion status shown here: https://curate.library.emory.edu/importers/586?file_set_entries_page=4&locale=en#file-set-entries . There are multiple FileSets here that are returning nil for the FileSet IDs. I can fix the regenerate manifest errors from the command line, but this shows another bug that is occurring with the import processing. I will create another bug ticket that examines why these are showing as complete whenever the FileSet creation process doesn't successfully persist.

**Comment by kmichaelis** [comment]
Thanks! Many if not all of these have filesets appended to the end that are out of order--after I manually attached them I wasn't able to get them to save in their proper position in the work. Would you be able to fix that?

**Comment by bwatson78** [comment]
Yes, you should be able to do that after I eliminate the empty values in `ordered_members`.

**Comment by kmichaelis** [comment]
Ok perfect!

**Comment by kmichaelis** [comment]
I just realized that the last link in the above list is a fileset...the correct link is
https://curate.library.emory.edu/concern/curate_generic_works/559q2bvs0b-cor?locale=en
Sorry about that!

**Comment by bwatson78** [comment]
All of the above mentioned works have been corrected by eliminating nil FileSet objects in the `ordered_members` attribute. I spoke to Collin about opening the bug ticket mentioned above and he advised to hold off on doing so. We have encountered some unexpected Curate downtime recently that may explain why this has occurred.
