### ISSUE TITLE
Two works whose filesets failed to attach

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2287]
Yesterday I ingested two works to Curate via Bulkrax. The final job to associate filesets with works kept showing up in the busy queue in Sidekiq, then moving to the scheduled queue, then back and forth for several hours until I eventually killed the jobs.

The message shown in the attached screenshot appeared in the dead queue during each ingest.<img width="1739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHN3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5c0a674d467550e1842164501fea178637fb4ab/Capture.PNG" alt="Capture.PNG" />

These are the works:

https://curate.library.emory.edu/concern/curate_generic_works/982x3ffftk-cor?locale=en
https://curate.library.emory.edu/concern/curate_generic_works/293gxd286v-cor?locale=en

**Comment by bwatson78** [comment]
I just analyzed the CsvEntry objects that this error occurs on, and the issue is that the parent column is being populated with barcode values. Specifically, one has the parent value as `barcode:70000029211`, and the other is populated with `barcode:990028548970302486`. That may be occurring because there may be a splitting indicator (a comma, pipe, or semicolon) that has been introduced somewhere during the processing of the CSV.

If you need assistance to remove the Works via the comman line, I'm glad to help.

**Comment by kmichaelis** [comment]
This shouldn't be a problem, we use a combination of "barcode:" and barcode value as deduplication keys frequently. I think all the other works in this collection have dedup IDs that are structured the same way.

**Comment by bwatson78** [comment]
Oh, apologies, wasn't aware that's a common deduplication key format now. Let me look deeper into this.

**Comment by bwatson78** [comment]
I just pulled the CSV for ` A few words to the soldiers of the Confederate States.` and the last FileSet has the wrong barcode number. Looking at the other item.

**Comment by bwatson78** [comment]
And I just found the odd barcode in the other CSV (L#5). I'm sending both to your slack, @kmichaelis

**Comment by kmichaelis** [comment]
Thank you! Closing this.
