### ISSUE TITLE
Introduce release numbering for Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#405]
Discussed release numbering scheme as incremental/patch numbers e.g.
0.3.0
0.3.1
0.3.2 etc.

**Comment by eporter23** [comment]
@bess @rotated8 tagging you guys on this - please revise this ticket as needed!

**Comment by eporter23** [comment]
@rotated8 well, that was fast!

**Comment by rotated8** [comment]
Reopening for some discussion. @bess, @mark-dce, @eporter23, please let me know if this fulfills the requirements we discussed earlier. Here's my plan:
- Each deploy will get a new release.
- Through the migration, each release will increment the patch number.
- After the migration, we will increment the minor version number.
- Each release will include release notes.
- Release notes will minimally include which commits were added and their commit messages.

**Comment by mark-dce** [comment]
This sounds great and I think the last two bullets are handled automatically by git.

Using Laevigata as an example, take a look at any specific release in the list: https://github.com/curationexperts/laevigata/releases?after=v2.3.5. Then all you need to do is look at the previous release, which will always include a note like "12 commits to master since this release" and a link to the commits in question.

So, for release [v2.3.2](https://github.com/curationexperts/laevigata/releases/tag/v2.3.2), you'd look for the prior release [v2.3.1](https://github.com/curationexperts/laevigata/releases/tag/v2.3.1) which indicates "[59 commits](https://github.com/curationexperts/laevigata/compare/v2.3.1...master) to master since this release" where the link provides you the full diff between release v2.3.1 and the following release.

As you can see from those releases, DCE's typical practices are to document the big ideas or user-level stories that got addressed in the release notes and use the functionality provided by GitHub when we need to look up commit-level information.

**Comment by mark-dce** [comment]
I think we've done this - eg: https://github.com/emory-libraries/dlp-curate/releases Is it OK to close this ticket?

P.S. AWESOME release notes for v0.3.1 - nice work @rotated8 !!!

**Comment by eporter23** [comment]
@mark-dce @rotated8 looks great to me! I'll close it.
