### ISSUE TITLE
(R-02)Security assessment - remediation work: CloudWatch Metric

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#607]
Description of the risk identified by the security team: https://emory.app.box.com/file/528500401683

**(R-02) Configuration Management: CloudWatch – Sensitive Data in Custom Metric:** An Emory user could create a custom metric that contains PHI or sensitive data.
 
**Security Recommendation:** When creating custom metrics within AWS CloudWatch, user must configure service in a way that does not capture any confidential data.

**Remaining work to do:** 
- [x] Document on the wiki the decision for the Library around PHI and/or sensitive data .

**Comment by eporter23** [comment]
Discussed in breakout meeting 7/13/20 - we don't know that snapshots are needed due to how we are doing backup and restoration. These volumes aren't necessarily in scope for backup and restoration of repository data. OS, applications, shibboleth, jetty, etc live on the EBS volume (but not repository data)

**Comment by eporter23** [comment]
Our policy document about PII is documented on the wiki and cross-referenced with this remediation item: https://wiki.service.emory.edu/display/DLPP/Security+and+Remediation+Documents
