### ISSUE TITLE
Investigate fixity service job provided by Hyrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#624]
- [x] Confirm if Hyrax only provides single file checking (and which one)
- [x] Confirm which queue(s) the job goes in
- [x] Check if job is queued for at the work level or a FileSet level

**Comment by devanshu-m** [comment]
Task 1 findings:
Fixity checking is performed on the following:
1) All file-types in the fileset (refer: https://github.com/samvera/hyrax/blob/master/app/services/hyrax/file_set_fixity_check_service.rb#L58)
2) All versions of a given file (refer: https://github.com/samvera/hyrax/blob/master/app/services/hyrax/file_set_fixity_check_service.rb#L76)

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/68032023-dc93-4eec-9fd6-39d592998eab)

^ what's happened here:
* First, I attached three files to a fileset, so I had 'Fixity check passed 3 files with 3 total versions checked'
* Then, I updated the version for the pmf, and ran fixity checking again, so now we have the new version. Therefore, 'Fixity check passed 4 files with 5 versions' (5, because it fixity checked the old and new version of pmf -- more on this when we get into versioning)
