### ISSUE TITLE
Large files do not attach or complete ingest

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#657]
Relates to other ticket #258 - see detailed test outcomes especially from October. See also this [sample work with files of various sizes](https://curate-test.library.emory.edu/concern/curate_generic_works/631cjsxkt6-cor?locale=en) attached.

Large files appear to upload, but they do not attach to FileSets or complete full characterization, checksum generation, etc. The individual files can't be located in Fedora.

_Mark's notes from 10/4:_

Found many of these in the Sidekiq log. Hope it helps.

{
"context": "Job raised exception",
"job": {
"class": "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",
"wrapped": "IngestJob",
"queue": "default",
"args": [
{
"job_class": "IngestJob",
"job_id": "eb782b27-e012-4406-b0a1-c468bc3e2659",
"provider_job_id": null,
"queue_name": "default",
"priority": null,
"arguments": [
{
"_aj_globalid": "gid://dlp-curate/JobIoWrapper/790"
}
],
"executions": 0,
"locale": "en"
}
],
"retry": true,
"jid": "40dfe2a01b6c2dbeb51ca54f",
"created_at": 1569867568.3141167,
"enqueued_at": 1570114051.2614255,
"error_message": "STATUS: 500 org.modeshape.jcr.value.binary.BinaryStoreException: org.modeshape.jcr.value.binary.BinaryStoreException: Unable to find binary value with key "da39a3ee5e6b4b0d3255bfef95601890afd80709" within binary store at "/tmp/modeshape-binary-store"\n\tat org.modeshape.jcr.value.binary.S3BinaryStore.storeValue(S3BinaryStore.java:231)\n\tat org.modeshape.jcr.value.binary.AbstractBinaryStore.storeValue(AbstractBinaryStore.java:251)\n\tat org.modeshape.jcr.value.binary.BinaryStoreValueFactory.create(BinaryStoreValueFactory.java:257)\n\tat org.modeshape.jcr.value.binary.BinaryStoreValueFactory.create(BinaryStoreValueFactory.java:49)\n\tat org.modeshape.jcr.JcrValueFactory.createBinary(JcrValueFactory.java:149)\n\tat org.modeshape.jcr.JcrValueFactory.createBinary(JcrValueFactory.java:41)\n\tat org.fcrepo.kernel.modeshape.FedoraBinaryImpl.setContent(FedoraBinaryImpl.java:179)\n\tat org.fcrepo.http.api.ContentExposingResource.replaceResourceBinaryWithStream(ContentExposingResource.java:623)\n\tat org.fcrepo.http.api.Fedo...",
"error_class": "Ldp::HttpError",
"failed_at": 1569867569.642823,
"retry_count": 16,
"retried_at": 1570048072.5132258
},
"jobstr": "{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"IngestJob","queue":"default","args":[{"job_class":"IngestJob","job_id":"eb782b27-e012-4406-b0a1-c468bc3e2659","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[{"_aj_globalid":"gid://dlp-curate/JobIoWrapper/790"}],"executions":0,"locale":"en"}],"retry":true,"jid":"40dfe2a01b6c2dbeb51ca54f","created_at":1569867568.3141167,"enqueued_at":1570114051.2614255,"error_message":"STATUS: 500 org.modeshape.jcr.value.binary.BinaryStoreException: org.modeshape.jcr.value.binary.BinaryStoreException: Unable to find binary value with key \"da39a3ee5e6b4b0d3255bfef95601890afd80709\" within binary store at \"/tmp/modeshape-binary-store\"\n\tat org.modeshape.jcr.value.binary.S3BinaryStore.storeValue(S3BinaryStore.java:231)\n\tat org.modeshape.jcr.value.binary.AbstractBinaryStore.storeValue(AbstractBinaryStore.java:251)\n\tat org.modeshape.jcr.value.binary.BinaryStoreValueFactory.create(BinaryStoreValueFactory.java:257)\n\tat org.modeshape.jcr.value.binary.BinaryStoreValueFactory.create(BinaryStoreValueFactory.java:49)\n\tat org.modeshape.jcr.JcrValueFactory.createBinary(JcrValueFactory.java:149)\n\tat org.modeshape.jcr.JcrValueFactory.createBinary(JcrValueFactory.java:41)\n\tat org.fcrepo.kernel.modeshape.FedoraBinaryImpl.setContent(FedoraBinaryImpl.java:179)\n\tat org.fcrepo.http.api.ContentExposingResource.replaceResourceBinaryWithStream(ContentExposingResource.java:623)\n\tat org.fcrepo.http.api.Fedo...","error_class":"Ldp::HttpError","failed_at":1569867569.642823,"retry_count":16,"retried_at":1570048072.5132258}"
}

**Comment by SolomonHD** [comment]
Update: I've been researching this problem the last few days and while I haven't solved it, there has been progress.

1. Iniitial problem was the curate app was not ever giving the 'Files Uploaded' message with larger files
  This was solved by pointing the environment variables responsible for the temporary upload space (UPLOAD_PATH, WORKING_PATH, CACHE_PATH) to local EBS storage instead of EFS, which is what they were pointed to before. I believe having the cache directories pointing to slower EFS was simply timing out for larger files. Note that there is still considerable time between when the progress bar fills and the 'Files Uploaded' message appears, about 90 secs for a 2 gig file to 5 minutes for a 3.5 GB file.
  
2. After this was fixed I was able to get a 1.2 GB file ingested into Fedora, I believe this is higher than what we could manage before this change. However going any higher resulted in Out of memory errors during the IngestJob with a 1.7GB video file.
    1. First I increased the memory of all Fedora instances to 16GB, that helped somewhat but I was still getting OutOfMemory errors when it seemed the ec2 instance had available memory
    2. Changed the maximum memory setting in Java Service Wrapper, after some research is appears the init and maxmemory settings had hard coded limits, so I decided to leave them blank and put -Xms -Xmx
    flags into the java additional section

3. The Java Service Wrapper changes got rid of the memory related errors (or so I thought!). Then I started having various 504 issues with the InjestJob which I interpreted as being timeout related.
    1. In the Fedora ec2 apache conf, I adjusted the ReadRequestTimeout for header and body to unlimited for the vhost
    2. Also In the AWS Console I increased the timeout for the cor ALB (which sits in front of all fedoras) to be 3600 secs.
 
4. 504 error codes ceased after those changes, but then I started getting application based errors: sometimes it was 400 Bad request, other times Faraday::TimeoutError: Net::ReadTimeout.
    1. I believe these are related to a timeout issue inside the code of the app. I've attempted to make code changes that would address this, to mixed results.
    2. I created a branch (file-size-increase-test) and deployed it to curate arch, the code changes were mostly in the initalizers/hyrax.rb and config/fedora.yml
    3.  I am still getting these Faraday errors after this change, occasionally I get the Java Out of Memory error instead.

5. After pushing those changes up to curate arch all 504 timeout errors went away. During my testing at this point I was able to successfully get a 1.9 GB file into fedora.

**Comment by eporter23** [comment]
I re-tested a 1.4 GB PDF file that had previously failed to ingest, and it attached successfully, was characterized, checksummed, etc. I noticed that some of @SolomonHD 's large test files did not seem to have completed their checksum generation etc however so I want to test a few more large files across the environments.

**Comment by eporter23** [comment]
The large PDF I uploaded does not successfully download from Curate, so this needs further testing.

**Comment by eporter23** [comment]
Closing this, but new ticket #755 created to address the download problem.
