### ISSUE TITLE
Index human-readable metadata fields

### ISSUE THREAD

**Issue by wulman16** [emory-libraries/dlp-curate#837]
https://docs.google.com/spreadsheets/d/1bODcf-cLwBNOv7UDtNE39M1OoRW93o6xRVDZMGX-eaQ/edit#gid=696928716

The Field Grouping sheet indicates which metadata fields must be indexed in a human-readable format for Lux. Based on the existing behavior in Curate, make the following changes:

**Make stored_searchable for Lux index**
- Issue (:issue)
- Grant/Funding Information (:grant_information_notes)

**Currently stored_searchable, but add a human-readable version to the Solr index for Lux:**
- Rights Statement - Controlled (:rights_statement)
- Re-Use License (:re_use_license)

**Comment by eporter23** [comment]
@wulman16 @nikdragovic note that Persistent URL (formerly known as primary_repository_ID) is now more of a display field than a metadata field. For Lux this is the NOID value we mint in Curate, reformatted into a persistent URL pattern. We opted to not store the NOID in primary_repository_ID because it was already in SOLR and searchable.

**Comment by wulman16** [comment]
After discussion with @eporter23 and @nikdragovic, the only change to Curate that needs to be made for metadata *display* in Lux is adding a human-readable version of Rights Statement - Controlled to the Solr index. The changes for metadata *search* in Lux will be addressed in a separate ticket in Lux.

**Comment by eporter23** [comment]
Discussed with team 7/29/20: our understanding is that all applicable human readable fields have been implemented as needed for Lux in Phase 1.
