### ISSUE TITLE
SPIKE: Sidekiq Preformance tuning

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#900]
- [x] Research running redis in Elasticache instead of on the server
- [x] Figure out best number of workers and the best queue weighting.
- [x] Fix process supervisor (systemd unit service) errors [Deploy doens't restart queue, just starts another one]

**Comment by rotated8** [comment]
@SolomonHD Is this ticket at a point we can pause it until we've met with @bess ?

**Comment by SolomonHD** [comment]
Currently sidekiq-capistrano branch is deployed to curate-test. This branch enables AWS elasticache redis instead of local.

@rotated8 Yes I think this is blocked until my changes to dlp-curate have been reviewed. Also I need for developers or to make sure the repo is still working for them locally after these changes.

**Comment by SolomonHD** [comment]
@rotated8 I believe the sidekiq-capaistrano branch is ready for merging. I've tested it on the server pointing to both localhost and external aws redis and it works either way. Also I ended up making the REDIS_HOST, REDIS_PORT, REDIS_DATABASE variables optional, if they're not defined they default to localhost, 6379 and 0 respectively.

**Comment by rotated8** [comment]
Reviewed, and made some changes. Would like @SolomonHD's thumbs up.
