### ISSUE TITLE
Update .env.production

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#939]
With @Bess's PR #934, the `.env.production` file will need to be updated to include the following:

`IIIF_SERVER_URL=https://hostname_for_curate_application/iiif/2/
PROXIED_IIIF_SERVER_URL=https://HOSTNAME_FOR_THE_ACTUAL_CANTALOUPE_SERVICE/iiif/2/`

**Comment by rotated8** [comment]
This is blocked, pending #934 getting merged.

**Comment by SolomonHD** [comment]
It shows #934 as merged so I assume this is unblocked

**Comment by SolomonHD** [comment]
.env.production has been updated on curate-arch. I will wait until this code is deployed on other servers before updating those.

**Comment by SolomonHD** [comment]
Bess and I updated curate-arch and curate-test with the new v.0.5.12 release and adjusted the .env variables accordingly.  We were getting an SSL error initially but after adjusting the .env file to use http instead of https for the cantaloupe url, we're getting a blank box instead of an error, indicating a problem with accessing the image. Bess is working to debug. I believe DevOps role in this issue is mostly done, so I'm closing the ticket.
