### ISSUE TITLE
Cantaloupe should report time to complete requests

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#970]
If available, Cantaloupe should log the time it takes to fulfill a request, for each request.

**Comment by tmiles2** [comment]
Has this been moved to inprogress or completed?

**Comment by tmiles2** [comment]
@mprefer Can I get an update on this work?

**Comment by mprefer** [comment]
Based on the Cantaloupe log file, it appears that most time is spent processing the image file in ImageMagick. Some images are processed more that once (to get different scales).

Have attempted to preload the cache, because cache hits bypass image processing.
Started with this url:
   http://10.65.89.44/cantaloupe/iiif/2/<file sha1>/full,600,0/default.jpg    In arch.
Still trying to determine where the other scaling factors "live"...some are in "info.json", some are not, but suspect Cantaloupe must calculate them?
The search continues, but to get reasonable performance, the filesystem cache will need to be seeded with processed images.

**Comment by tmiles2** [comment]
To close out this ticket:
- [ ] Create a list of times for image magic processing from Sha 1 
- [ ] Total time in Cantaloupe it takes to complete a request

**Comment by mprefer** [comment]
Average of 20 samples during ImageMagick processing: 3.75/s
