### ISSUE TITLE
Document how to clear Cantaloupe's cache

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#971]
In order to benchmark how long a Cantaloupe request takes, we would like to be able to ensure the requested image is not being cached.

**Comment by mprefer** [comment]
Using curl, the following API call will clear the image and info cache:

curl -u iiifadmin:b3gZSej3jJpu 'http://iiif-cor.library.emory.edu/cantaloupe/tasks' -H "Content-Type: application/json" --data-binary '{ "verb" : "PurgeCache" }'

I had to move the location of the cache, since it's prior location yielded no cached items.
