### ISSUE TITLE
Allow the Minter to ignore already minted IDs

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#997]
Currently, the minter has no checks in place in case it tries to reuse an ID. Even though it should not get into a state where it is trying to reuse an ID, we should check if an ID is usable before returning it.

- [x] Minter checks if an ID is in use, and returns the ID if it is not.
- [x] Minter creates the next ID if it is, and checks it as above.

**Comment by devanshu-m** [comment]
Notes:

* Sometimes the minter goes into a locked state when it tries
creating resources using IDs that are already taken or gone in
Fedora. In order to make sure that a resource is only created on an
unused valid ID, we loop through IDs until we find one that is not
previously assigned to any resource in Fedora.
